[project]
name = "async-processing"
version = "0.1.0"
description = "Асинхронный сервис процессинга платежей"
authors = []
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "fastapi (>=0.116.2,<0.117.0)",
    "uvicorn (>=0.37.0,<0.38.0)",
    "pydantic (>=2.11.9,<3.0.0)",
    "pydantic-settings (>=2.11.0,<3.0.0)",
    "sqlalchemy[asyncio] (>=2.0.44,<3.0.0)",
    "greenlet (>=3.2.0,<4.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "alembic (>=1.16.5,<2.0.0)",
    "faststream[cli,rabbit] (>=0.7.1,<0.8.0)",
    "httpx (>=0.28.1,<0.29.0)",
]

[tool.poetry]
packages = [
    { include = "bootstrap", from = "src" },
    { include = "payments", from = "src" },
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.15.9,<0.16.0)",
    "mypy (>=1.20.0,<2.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-asyncio (>=1.3.0,<2.0.0)",
]

[tool.ruff]
src = ["src", "cli", "tests"]
exclude = ["migrations/versions"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "C4", "N", "UP", "SIM", "RUF"]
ignore = ["RUF001", "RUF002", "RUF003", "E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["bootstrap", "cli", "payments"]
lines-after-imports = 2

[tool.mypy]
mypy_path = "src"
python_version = "3.12"
strict = true
plugins = ["pydantic.mypy"]

[tool.pytest.ini_options]
pythonpath = [".", "src"]
testpaths = ["tests"]
asyncio_mode = "auto"
